language: java
install: skip
os: linux
jdk: openjdk14
deploy:
  provider: heroku
  api_key:
    secure: kH+bGlxajGHsIyYQtzSLw/RS27R7PaDtw2sXIdDxrklVVaBUz/Hc4YOkUoEWgxayxb9YhANUjEAGlw/HGPosvpz/at2JIk/uuRinND5U09dW0mVbWkS+M+FfnEbTHrp3i3iT5s0+KbDBgeaz3p/wOKAprd4cQQ57dExsYj2TfkzczPnWCJwaC/ji6SKQtYqewum3cnsVfiDtZTaGd9homIP64Bw/76XpVjFgJHpbOiYzxByjgsZtgUxbEfsrvISJD+rix9LmzvlCL0Ei9UC7T2kuYfWQgZwSUmfpxYYocpLXRKi6H69n3gecUDWNRafsh9/fQteBw9Aw+LhSNFrFqmoX91v/dB/ZK3qFO8SOp1A7Y2lUctwyTNwbWSqgPjjVSjqeWE4ZIpEkn2lIWBLPMEzpV3uOQx35QiTDwwA0/yVwBcxlF+XGh5NM5izZB0TFJvLyo/7Bu05B5Un2mOOfE12k6Q0lAsqiK7bf8yYEe0yeqlJz7N/7/N7QnlVCKZdtuDxG/0JZMi6M9AegoQnzLNuPPtVTQEDx8MAktnanKzjT6h6VEiUTdLn2QBZhsJgINmnvc+vVOac87cgo4StrKnAXIEUdk5mv0gPYZ0sM4Dp7+Q++BCjyPzVB9rzrQj+hIXTckeCF1BicxfAI5aaR2/0qqVUkdi2K7yHQ9eyE3Go=
  on:
    repo: Kidboo10/helloTest
addons:
  sonarcloud:
    organization: kidboo10
    token:
      secure: l/zI07q+ba0gHEEGexUlOSkTjQEp02CYu/uUR0R5mzM5E5OWFRWO44Y7TKt6ryIxOmiTgT0EcMsiojVPM/aj/1j8LXqxluDFi8lKXTn7dxNgbEAxlc+3SmRL1W2eJjfgi67yOubu9SuhWhaBmVtZAwREUIy2vSpJBoWI6MBKqX83n7Lkt0CLy1xHMSHBokSfhyEPSXpcSVcnN8B7NdM86W9YShE62fAsLGe7mqiTzyQ/Zv0k1YJuWUtqE4xkhJeFeXxurji0F/+fglEf8VMwahxCQ8BZyCvP1YMhJVki5VROKCa5lTcJtptKJKKZLNkq/nUKeas33OAs0l2UqownQaycHABcAXIOLOVaHQInVcrVgFtgzDUfYNEVgeQ1HujUCEgfjotVpK0amDOnk4U4+/c99pRF+LNDF52vuI/TdokphetT9mNhV33gk32saDqUPzGKhfwucKtDLt1eaWSJXwDxxW+43pTdpWSW9+Tqj5VEz6z56fh8xR75SwTYNR1U3u1pRWMpXBag8JH9qTeIfNfk9wgbi+6QNCXCYXzL6Zvb23eeEbrdQ8cTXxuzhZ7ahedyhq2NvGUE00Tn+4AKjnsXp2KBOJH9Rv30846W0eMOXI5kHi3h4zslWq1pd1TWu3rRwKJ2zyzmyWhT9ZmFPympHTOGP97w2E/My4vKByI=
script:
- chmod +x ./gradlew
- "./gradlew clean build"
- "./gradlew sonarqube"
