language: java
install: skip
os: linux
jdk: openjdk14
deploy:
  provider: heroku
  api_key:
    secure: jUL41X+/Y51Plb3a7uA8YEXkDWtbtKbMd1I96MeESdj8tBYJka3Zi0jRs1uZEcqwhLbiBV4zNjAl6VeiXJEJnRrJGoOvFiz96lxTnPKJj0tHQa6veMXN9FaTPys9FsP862FGMkVZtL4nqj3c1h1sdpiwUiIpmZpspDtWBQNShmYu4SdO4+Kftg+P8N/pyz2EM8IAmqlW229aG64i5a9cOq8uTcYOSdSheFGJsKQbr/pn3MdoO6dzFGAafteas4dvKnEJj4GVdjnGG3Uh+64BvsgE9ihX5V4FLp+D5cbLNB+3HABgg1o0fpB76d8hPfMji6nMgdyfPV9n4eT8UnMm3abxaCwHYH829BcWHC+Leqg7Zz+BT7ZVdVijN8vGfvWmvr3+ksMgyEn2fwmdMDEefkWhl7njxILa2aBwG7SqP/oqlUUsoLT2PwSfSNiGMQOvboILoV2cIusHRfzERFOyTmNocKVQixelS3wWQzpvn53idmlbnf1nKa8lWjkwg+J90yejKjblAj/DnO6YKgtWEpbg41qWo/jgLb5MpkIMb5pMpG9zYXyfGHSPQ8SnXMG86gbQvZdJnI5ADcU+4r7ynxPU5t/BdkuR/dB4CSMWTQFqj6r44VKoEvURdFTVs19emsY2bB/QkGahveOv6ylvY/W8FS0brbxlOBb/DPUauSE=
  app: hellopipe
  on:
    repo: Kidboo10/helloTest
addons:
  sonarcloud:
    organization: "Kidboo10"
    token:
      secure: l/zI07q+ba0gHEEGexUlOSkTjQEp02CYu/uUR0R5mzM5E5OWFRWO44Y7TKt6ryIxOmiTgT0EcMsiojVPM/aj/1j8LXqxluDFi8lKXTn7dxNgbEAxlc+3SmRL1W2eJjfgi67yOubu9SuhWhaBmVtZAwREUIy2vSpJBoWI6MBKqX83n7Lkt0CLy1xHMSHBokSfhyEPSXpcSVcnN8B7NdM86W9YShE62fAsLGe7mqiTzyQ/Zv0k1YJuWUtqE4xkhJeFeXxurji0F/+fglEf8VMwahxCQ8BZyCvP1YMhJVki5VROKCa5lTcJtptKJKKZLNkq/nUKeas33OAs0l2UqownQaycHABcAXIOLOVaHQInVcrVgFtgzDUfYNEVgeQ1HujUCEgfjotVpK0amDOnk4U4+/c99pRF+LNDF52vuI/TdokphetT9mNhV33gk32saDqUPzGKhfwucKtDLt1eaWSJXwDxxW+43pTdpWSW9+Tqj5VEz6z56fh8xR75SwTYNR1U3u1pRWMpXBag8JH9qTeIfNfk9wgbi+6QNCXCYXzL6Zvb23eeEbrdQ8cTXxuzhZ7ahedyhq2NvGUE00Tn+4AKjnsXp2KBOJH9Rv30846W0eMOXI5kHi3h4zslWq1pd1TWu3rRwKJ2zyzmyWhT9ZmFPympHTOGP97w2E/My4vKByI=
script:
  - chmod +x ./gradlew
  - "./gradlew clean build"
  - "./gradlew sonarqube"